version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: universidadesdb
      POSTGRES_HOST: postgres 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - datalogger_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@jasoft.ec
      PGADMIN_DEFAULT_PASSWORD: clave
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - datalogger_net

  universidades:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=universidadesdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JAEGER_AGENT_HOST=jaegertracingio
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["sh", "-c", "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0"]
    networks:
      - datalogger_net

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: c:/Users/Diego/datapg

networks:
  datalogger_net:
    driver: bridge