apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Diego\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: universidades
  name: universidades
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: universidades
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Diego\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/universidades-datalogger-net: "true"
        io.kompose.service: universidades
    spec:
      containers:
        - args:
            - sh
            - -c
            - /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: universidadesdb
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: JAEGER_AGENT_HOST
              value: jaegertracingio
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_SAMPLER_TYPE
              value: const
          image: universidades
          name: universidades
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
